---
title: "T cell transfer single cell analysis - Epithelial fraction"
editor_options:
  chunk_output_type: console
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
params:
  dataset: 1
---

```{r Setup, echo = FALSE}
knitr::opts_chunk$set(fig.width  = 10,
                      results    = "hold",
                      message    = FALSE,
                      warning    = FALSE)


```

```{r setup}

library(Seurat)
library(ggplot2)
library(cowplot)
library(clustree)

library(future)
plan("sequential")
options(future.globals.maxSize = 50 * 1024^3)

source("../code/SingleCell/color_list.R")
source("../code/SingleCell/NMFsetup.R", chdir = TRUE)


```

```{r}
 
datadir = "../data/SingleCell/TcellTransfer/R_objects_1/"

owncache = "../data/SingleCell/TcellTransfer/cache_epithelial/"

violintheme = theme(axis.text = element_text(size = 8),
        plot.title = element_text(size = 8),
        legend.key.size = unit(8, "pt"),
        axis.title = element_blank())
dimtheme = theme(legend.text = element_text(size = 8),
        plot.title = element_text(size = 8),
        legend.key.size = unit(8, "pt"))

qc_feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo")

```

```{r, include = FALSE}

if(file.exists(owncache)){
  message(paste0("Intermediate data files will be loaded from and saved to ",owncache))
}else{
  message("Intermediate data files will not be saved or loaded")
}

```

# Initial data 


```{r loaddata}

alldata = readRDS(paste0(datadir,"epithelial_data.rds"))

alldata = SetIdent(alldata, value = "orig.ident")

alldata <- AddMetaData(alldata, log10(alldata$nFeature_RNA), "logFeatures")


limits = data.frame(orig.ident = c('G_D0_E_ut', 'G_D10_E_ut', 'G_D20_E_ut', 'G_D30_E_il', 'G_D40_E_il',
                               'G_D40_E_ut', 'G_D50_E_ut', 'G_D60_E_il', 'G_D60_E_ut', 'G_W0_Epi', 
                               'G_W1_Epi', 'G_W2_Epi', 'G_W3_Epi', 'G_W3_Epi_aIL12', 'G_W4_Epi',
                               'G_W5_Epi', 'G_W5_Epi_aIL12', 'G_W6_Epi', 'G_W7_Epi', 'G_W7_Epi_aIL12'),
density = NA)





for(x in sort(unique(alldata$orig.ident))){
  dens = density(alldata@meta.data[alldata@meta.data$orig.ident %in% x,]$logFeatures)
  maxima = dens$x[which(diff(sign(diff(dens$y)))==-2)+1]
  maxima_y = dens$y[which(diff(sign(diff(dens$y)))==-2)+1]
  maxima = maxima[maxima_y>0.01]
  minima = dens$x[which(diff(sign(diff(dens$y)))==2)+1]
  minima_y = dens$y[which(diff(sign(diff(dens$y)))==2)+1]
  minima = minima[minima<max(maxima)]
  limits[match(x, limits$orig.ident),"density"] = max(minima)
  
}

  ggplot(alldata@meta.data, aes(x = logFeatures)) + geom_density() +
    geom_vline(data = limits, mapping = aes(xintercept = density)) + 
    facet_wrap(~orig.ident)
  
  goodcells = Cells(alldata)[alldata$logFeatures > limits$density[match(alldata$orig.ident, limits$orig.ident)]]
  
  alldata <-  subset(alldata, cells = goodcells)
  

```

```{r normalize}

if(!file.exists(paste0(owncache,"first_dr.RData"))){

DefaultAssay(alldata) = "RNA"



suppressWarnings(
  suppressMessages(
    alldata <-FindVariableFeatures(alldata, selection.method = "vst", 
                                   nfeatures = 2000, verbose = FALSE,
                                   assay = "RNA")))

  alldata <- ScaleData(alldata, vars.to.regress = c("percent_mito", "nFeature_RNA"), 
      assay = "RNA")
  alldata <- RunPCA(alldata, npcs = 50, verbose = F)
  alldata <- RunUMAP(alldata, reduction = "pca", dims = 1:30, 
                     n.components = 2, n.neighbors = 30, 
      n.epochs = 200, min.dist = 0.3, learning.rate = 1, 
      spread = 1, reduction.name = "umap")
  
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache,"first_dr.RData"))
  }
}else{
  load(paste0(owncache,"first_dr.RData"))
}


```


# Plot QC vars

Number of features and counts and percentage of mitochondrial and ribosomal RNA are plotted below.

```{r qc, fig.height=4, fig.width=6}

VlnPlot(alldata, group.by = "orig.ident", features = qc_feats, pt.size = 0, ncol = 2) &
  violintheme

```

# Highly variable features

```{r topgenes, fig.height = 3, fig.width = 5}

top20 <- head(VariableFeatures(alldata), 20)
lp = LabelPoints(plot = VariableFeaturePlot(alldata), points = top20, repel = TRUE) +
  theme(axis.title = element_text(size = 8),
        legend.text = element_text(size = 8),
        axis.text = element_text(size = 8))

lp$layers[[2]]$aes_params$size = 3

lp

```

# PCA

```{r, fig.height = 3, fig.width = 6}

plot_grid(ncol = 3, 
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident", 
                  dims = 1:2, shuffle = TRUE) +
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)),
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident", 
                  dims = 3:4, shuffle = TRUE) + 
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)),
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident",
                  dims = 5:6, shuffle = TRUE) + 
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)))

```


```{r, fig.height = 3, fig.width = 6}

VizDimLoadings(alldata, dims = 1:5, reduction = "pca", ncol = 5, balanced = T) &
  theme(axis.text = element_text(size = 8), axis.title = element_text(size = 8))

```


```{r, fig.height = 2, fig.width = 4}

ElbowPlot(alldata, reduction = "pca", ndims = 50) + 
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8))

```

# UMAP

```{r firstumap, fig.height = 3, fig.width = 6}

plot_grid(ncol = 2, DimPlot(alldata, reduction = "pca", raster = TRUE,
                            group.by = "orig.ident", shuffle = TRUE) + 
            NoLegend() + NoAxes() + dimtheme, 
    DimPlot(alldata, reduction = "umap", group.by = "orig.ident", raster = TRUE,
            shuffle = TRUE) +
      NoLegend() + NoAxes() + dimtheme)

plot_grid(ncol = 2, DimPlot(alldata, reduction = "umap", raster = TRUE,
                            group.by = "orig.ident", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme, 
          DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "Model", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme)

plot_grid(ncol = 2, DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "Treatment", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme,
          DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "RPCA_cluster", label = TRUE, shuffle = TRUE) + 
            NoLegend() + NoAxes() + dimtheme)

FeaturePlot(alldata, reduction = "umap", features = c("Ptprc","Epcam"), raster = TRUE,
    order = T, slot = "data", combine = T) & dimtheme & NoAxes() & NoLegend()

```


# Integration


```{r}



if(!file.exists(paste0(owncache,"integration.RData"))){
  if(!file.exists(paste0(owncache,"anchors.RData"))){
    
    plan("sequential")

    alldata <- SplitObject(alldata, split.by = "orig.ident")
    
    alldata = lapply(alldata, function(x){
      message(length(Cells(x)))
        x <- NormalizeData(x, verbose = FALSE)
        x <- FindVariableFeatures(x, selection.method = "vst",
                nfeatures = 2000, verbose = FALSE)
      })
       
   # Fails on 128GB with 6 workers 
    plan("multisession", workers = 3, gc = TRUE)
    data.anchors <- FindIntegrationAnchors(object.list = alldata, 
                                                dims = 1:30, reduction = "cca")
    rm(alldata)
    gc()

    if(file.exists(owncache)){
          save(data.anchors, file = paste0(owncache,"anchors.RData"))
    }
  }else{
    rm(alldata)
    gc()
    load(paste0(owncache,"anchors.RData"))
  }
  
  plan("multisession", workers = 6, gc = TRUE)
  alldata <- IntegrateData(anchorset = data.anchors, dims = 1:30, new.assay.name = "CCA",
         sample.tree = matrix(c(-5,-4, 1,2,3,-3,5,-9,-12,4,6,-7,8,12,7,-2,
                                13,17,18, -17,-11,-16,-6,-8,-13,-19,-20,-1,
                                -15,-14,-18,10,-10,11,9,14,15,16), ncol = 2))
  
  rm(data.anchors)
  gc()
  
  alldata <- ScaleData(alldata)
  alldata <- RunPCA(alldata, npcs = 30, verbose = FALSE)
  alldata <- RunUMAP(alldata, dims = 1:30)
  
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache,"integration.RData"))
  }
}else{
  load(paste0(owncache,"integration.RData"))
}

plan("sequential")

```

```{r, fig.height = 2, fig.width=5}

plot_grid(ncol = 2,
  
  DimPlot(alldata, reduction = "pca", group.by = "orig.ident", pt.size = 0.01, shuffle = TRUE) +
    NoAxes() + ggtitle("PCA integrated") + NoLegend() + dimtheme,
  DimPlot(alldata, reduction = "umap", group.by = "orig.ident", pt.size = 0.01, shuffle = TRUE) +
    NoAxes() + ggtitle("UMAP integrated") + NoLegend() + dimtheme
)

alldata@active.assay = "RNA"
FeaturePlot(alldata, reduction = "umap", features = c("Ptprc","Epcam"), 
    order = T, slot = "data", combine = T) & dimtheme & NoAxes()
alldata@active.assay = "CCA"

```



```{r, fig.height = 6, fig.width=4}

FeaturePlot(alldata, reduction = "umap", 
            features = c("percent_mito","percent_ribo","S.Score",
                         "G2M.Score", "nFeature_RNA"), 
    order = T, slot = "data", combine = T, ncol = 2) &
  NoAxes() & NoLegend() & dimtheme

```



# Clustering

```{r}

if(!file.exists(paste0(owncache, "clustered.RData"))){
  alldata@active.assay <- "CCA"
  
  alldata@active.assay

  alldata <- FindNeighbors(alldata, dims = 1:30, k.param = 350, prune.SNN = 1/15)

  
  # Clustering with louvain (algorithm 1)
  for (res in c(0.25, 0.5, 1, 1.5)) {
      alldata <- FindClusters(alldata, graph.name = "CCA_snn",
                              resolution = res, algorithm = 1)
  }
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache, "clustered.RData"))
  }
}else{
  load(paste0(owncache, "clustered.RData"))
}



```



```{r dimplots, fig.height=6, fig.width = 6}

plot_grid(ncol = 2, 
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.0.25",
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_0.25"),
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.0.5", 
                  label = TRUE) + dimtheme +  NoLegend() + NoAxes() + 
            ggtitle("louvain_0.5"),
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.1", 
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_1"), 
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.1.5", 
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_1.5"))


```


```{r clustreeplot}

clustree(alldata@meta.data, prefix = "CCA_snn_res.")

```


```{r}

clusternames = 
  data.frame(Cluster = 0:12, 
             epi_clusters = c("TA G2-M","Goblet Ccl6","TA S-G2","Colonocytes Areg",
    "Goblet Mptx1","Colonocytes Car1","ISC","TA G1-S",
    "Early EEC","Goblet Reg4","M cells","Late EEC","Tuft")
             )
clusterorder = c("ISC","TA G1-S","TA S-G2","TA G2-M",
                 "Colonocytes Areg","Colonocytes Car1",
                 "M cells","Goblet Ccl6","Goblet Mptx1",
                 "Goblet Reg4","Early EEC","Late EEC","Tuft")


alldata = AddMetaData(alldata, 
                      factor(clusternames$Clustername[
                        match(alldata$CCA_snn_res.0.5,clusternames$Cluster)], 
                        levels = clusterorder),
                      "NamedCluster")

alldata = SetIdent(alldata, value = "NamedCluster")

color_list = get_color_list(13)
names(color_list) = clusterorder

```

```{r, fig.height = 4, fig.width = 4}

dp = DimPlot(alldata, label = TRUE, shuffle = TRUE) + 
  NoAxes() + NoLegend() + dimtheme + scale_color_manual(values = color_list)

dp$layers[[2]]$aes_params$size = 3

dp

```

# Differential expression

```{r}

sel.lev = 0.5
sel.clust = paste0("CCA_snn_res.",sel.lev)

alldata <- SetIdent(alldata, value = sel.clust)

```

```{r}

markers_genes <- FindAllMarkers(alldata, logfc.threshold = 0.2, test.use = "wilcox", 
    min.pct = 0.1, min.diff.pct = 0.2, only.pos = TRUE, max.cells.per.ident = 1000, 
    assay = "RNA", random.seed = 42)

top25 <- markers_genes %>% group_by(cluster) %>% top_n(-25, p_val)

mypar(2, 5, mar = c(4, 6, 3, 1))
for (i in unique(top25$cluster)) {
    barplot(sort(setNames(top25$avg_log2FC, top25$gene)[top25$cluster == i], F),
            horiz = T, 
        las = 1, main = paste0(i, " vs. rest"), border = "white", yaxs = "i")
    abline(v = c(0, 0.25), lty = c(1, 2))
}

```


```{r}

markergenes = 
  c("Stmn1","Lgr5","Ascl2","Smoc2","Hells","Mcm6","Pcna","Top2a","Mki67",
    "Hist1h2ap","Ccnb2","Cenpa","Cdc20","Muc3","Areg","Sycn","Wfdc2",
    "Lgals3","Car1","Ccl20","Ubd","Clu","Tnf","Muc2","Ang4","Agr2",
    "Ccl6","Mptx1","Reg4","Chga","Chgb","Pyy","Cck","Dclk1")



```

```{r dotplot, fig.height = 2.2, fig.width = 6}

alldata@active.ident = factor(alldata$namedcluster, levels = rev(clusterorder))
dot = DotPlot(alldata, features=markergenes)
dot = dot + aes(x = id, y = features.plot) +
  scale_y_discrete(position = "right") + 
  coord_flip() + 
  labs(y = "Genes",x = "Clusters") + 
  scale_size(range = c(0.5,2.5), breaks = c(0,50,100), limits = c(0,100)) +
  theme(legend.position = "right", legend.title = element_blank(),
        axis.text.x.top = element_text(size = 6, angle = 90, vjust =0.5,
                                   hjust = 0, face = "italic"),
        axis.text.y = element_text(size = 6),
        legend.key.width = unit(0.3, "cm"), 
        legend.key.height = unit(0.3,"cm"), 
        legend.text = element_text(size = 6),
        axis.title = element_text(size = 8))
dot$scales$scales[[1]]$limits = c(-1.8,2.7)

print(dot)

```

```{r annotateddimplot}

plot_grid(ncol = 2, DimPlot(alldata, label = T, group.by = "namedcluster") +
            NoAxes() + NoLegend() + scale_color_manual(values = color_list))

```

# Population changes over time

```{r}

clean_sample_names = function(sam){
  for(s in c("_Imm","I_","_Epi","_E","_Str","S_","_ut","G_", "_aIL12","_il")){
    sam = gsub(s, "",sam)
  }
  sam
}

```



```{r}

frequencies = as.data.frame(table(data.frame(cluster=metadata_all[,sel.clust],
                 sample = metadata_all$orig.ident, model = metadata_all$Model)))
frequencies$Proportion=NA
for(i in 1:nrow(frequencies)){
  frequencies$Proportion[i] =
    frequencies$Freq[i]/
    sum(frequencies$Freq[frequencies$sample==frequencies$sample[i]])
}

frequencies$time = metadata_all$Time[match(frequencies$sample, metadata_all$orig.ident)]
frequencies$treatment = metadata_all$Treatment[match(frequencies$sample, 
                                                     metadata_all$orig.ident)]

frequencies$namedcluster = clusternames[match(frequencies$cluster,
                                              clusternames$Cluster),
                                   paste0(celltype,"_clusters")]
frequencies$namedcluster = factor(frequencies$namedcluster, 
                                  levels = clusternames[
                                    clusternames[,paste0(celltype,"_order")]!="",
                                    paste0(celltype,"_order")])

cumulFreq = frequencies
cumulFreq$cumulProp = NA
for(i in unique(cumulFreq$sample)){
  cumulFreq$cumulProp[cumulFreq$sample %in% i] = rev(cumsum(rev(cumulFreq$Proportion[cumulFreq$sample %in% i])))
}
cumulFreq = rbind(cumulFreq,cumulFreq)
cumulFreq$xadj = rep(c(-1,1), c(nrow(frequencies),nrow(frequencies)))
cumulFreq$oldtime = cumulFreq$time
cumulFreq$time = as.numeric(gsub("D","",gsub("W","",as.character(cumulFreq$time))))


cleanfrequencies = frequencies[
  (substr(frequencies$time,1,1) == "W" & frequencies$model == "SCID") |
    (substr(frequencies$time,1,1) == "D" & frequencies$model == "Rag2"),]

clustercors = lapply(c("SCID","Rag2"), function(bg){
  corlist = lapply(unique(cleanfrequencies$namedcluster), function(i){
    clufreq = cleanfrequencies[cleanfrequencies$namedcluster==i  & 
                          cleanfrequencies$treatment == "untreated" & 
                          cleanfrequencies$model == bg,]

    clucor = cor(clufreq$Proportion,as.numeric(as.factor(as.character(clufreq$time))))
    clucor
    })
  names(corlist) = unique(cleanfrequencies$namedcluster)
  corlist
  })
names(clustercors) = c("SCID","Rag2")

averagecor = lapply(1:length(clustercors[[1]]), function(i){
  mean(c(clustercors[[1]][[i]], clustercors[[2]][[i]]))
})
names(averagecor) = names(clustercors[[1]])

cleanfrequencies$namedcluster = 
  factor(cleanfrequencies$namedcluster, 
         levels = names(averagecor)[order(unlist(averagecor), decreasing = TRUE)])
cumulFreq$namedcluster = 
  factor(cumulFreq$namedcluster,
         levels = names(averagecor)[order(unlist(averagecor), decreasing = TRUE)])

cleanfrequencies$sample = 
  factor(cleanfrequencies$sample, 
         levels = 
           unique(cleanfrequencies$sample[
             order(factor(cleanfrequencies$model, levels = c("SCID","Rag2")),
                   cleanfrequencies$treatment,
                   cleanfrequencies$time)]))
cleanfrequencies$samplenumber = as.numeric(cleanfrequencies$sample)

cumulFreq = cumulFreq[paste(cumulFreq$sample,
                cumulFreq$model,
                cumulFreq$oldtime) %in% 
            paste(cleanfrequencies$sample,
                  cleanfrequencies$model,
                  cleanfrequencies$time),]

cumulFreq$sample =
  factor(cumulFreq$sample, 
         levels = 
           unique(cumulFreq$sample[order(factor(cumulFreq$model, levels = c("SCID","Rag2")),
                                         cumulFreq$treatment,
                                         cumulFreq$time)]))
cumulFreq$samplenumber = as.numeric(cumulFreq$sample)


datasets = lapply(names(clustercors), function(bg){
  bgfreq = cleanfrequencies[cleanfrequencies$model == bg,]
  bglist = lapply(unique(bgfreq$treatment), function(i){
    trfr = bgfreq[bgfreq$treatment==i,]
    cumtrfr = cumulFreq[paste(cumulFreq$sample,
                                     cumulFreq$model,
                                     cumulFreq$oldtime) %in% 
                                 paste(trfr$sample,
                                       trfr$model,
                                       trfr$time),]
    list(trfr, cumtrfr)
  })
  names(bglist) = unique(bgfreq$treatment)
  bglist
})

barplot = ggplot(data = cleanfrequencies, 
       aes(x = samplenumber, y = Proportion, fill = namedcluster)) + 
  theme(panel.background = element_blank(), axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
            scale_fill_manual(values =
                                color_list[as.character(unique(sort(bgfreq$namedcluster)))]) + 
            scale_x_continuous(breaks = sort(unique(cleanfrequencies$samplenumber)),
                               labels = clean_sample_names(levels(cleanfrequencies$sample)))

for(ds in datasets){
  for(dst in ds){
    barplot = barplot + 
      geom_area(data = dst[[2]],
                alpha = 0.7, size = 0.3, stat = 'identity',
                aes(fill = namedcluster, group = namedcluster,
                    y = Proportion, x = samplenumber + xadj*0.3))}
}

barplot + geom_bar(stat = "identity", width = 0.6, color = "black")

```

# Subset analyses


```{r}

alldata = AddMetaData(alldata, alldata$NamedCluster, "stemcolono")
alldata = AddMetaData(alldata, alldata$NamedCluster, "goblet")

alldata$stemcolono[!(alldata$stemcolono %in% 
                  c("ISC","TA G1-S","TA S-G2","TA G2-M",
                 "Colonocytes Areg","Colonocytes Car1"))] = NA

alldata$goblet[!(alldata$goblet %in% 
                  c("Goblet Ccl6","Goblet Mptx1", "Goblet Reg4"))] = NA


```

```{r, fig.height = 3, fig.width = 9}

plot_grid(plotlist = lapply(c("stemcolono","goblet"),
       function(x){
         dp = DimPlot(alldata, group.by = x, label = TRUE, shuffle = TRUE) +
            scale_color_manual(values = color_list, na.value = "#CACACA") +
            dimtheme & NoLegend() & NoAxes()
         dp$layers[[2]]$aes_params$size = 3
         dp
       }), ncol = 3)

```

```{r}

stemcolono = 
  subset(alldata, 
         cells = WhichCells(alldata, expression = 
                              stemcolono %in% alldata$NamedCluster))
goblet = subset(alldata, cells = WhichCells(alldata, expression = goblet %in% alldata$NamedCluster))

rm(alldata)
gc()

```


# NMF

```{r subsetting}


# Making subsets

## CD4

CD4_color_list = color_list
CD4_color_list[!(names(color_list) %in% clusterorder[1:4])] = NA
DimPlot(alldata, group.by = "Named_cluster") + 
  NoLegend() + NoAxes() +
  scale_color_manual(values = CD4_color_list)

CD4data = subset(alldata, idents = c(0,2,12,16))

CD4data = CD4data[,CD4data$RelTime > 0.1]

DefaultAssay(CD4data) = "RNA"
CD4data[["CCA"]] = NULL

CD4data <- ScaleData(CD4data)
CD4data <- RunPCA(CD4data, npcs = 30, verbose = FALSE)
CD4data <- RunUMAP(CD4data, dims = 1:30)

CD4data <- FindVariableFeatures(CD4data)
CD4data <- ScaleData(CD4data, features = VariableFeatures(CD4data))

## Neutrophils

neutrophil_color_list = color_list
neutrophil_color_list[!(names(color_list) %in% "Neutrophils")] = NA
DimPlot(alldata, group.by = "Named_cluster") + 
  NoLegend() + NoAxes() +
  scale_color_manual(values = neutrophil_color_list)

neutrophildata = subset(alldata, idents = 10)

DefaultAssay(neutrophildata) = "RNA"
neutrophildata[["CCA"]] = NULL

neutrophildata <- ScaleData(neutrophildata)
neutrophildata <- RunPCA(neutrophildata, npcs = 30, verbose = FALSE)
neutrophildata <- RunUMAP(neutrophildata, dims = 1:30)

neutrophildata <- FindVariableFeatures(neutrophildata)
neutrophildata <- ScaleData(neutrophildata, features = VariableFeatures(neutrophildata))


rm(alldata)
gc()

```


## Progenitors and colonocytes



```{r}

ntop = 40
downsample_n = 1000
txt = element_text(size = 8)

```


```{r}

stemcolono@active.assay <- "RNA"


stemcolono <- FindVariableFeatures(stemcolono)
stemcolono <- ScaleData(stemcolono, features = VariableFeatures(stemcolono))

stemcolono <- RunNMF(object = stemcolono, assay = "RNA", nfactors = ntop,
              n.cores = 1)
 

for(i in 1:ntop){
  stemcolono <- AddMetaData(stemcolono, stemcolono@reductions$NMF@cell.embeddings[,paste0("factor_",i)],
                     paste0("nmf_",i))
}

stemcolono$Week = as.numeric(gsub("W","",stemcolono$Week))

stemcolono = AddMetaData(stemcolono, factor(paste(stemcolono$Genotype, stemcolono$Week),
                              levels = c("WT 6", 
                                         paste0("Il10KO ", 
                                               c(6,8,10,12,14)))), 
                  "G_W")

```

```{r}

pvaluelist = getfactorpvalues_Il10(stemcolono, downsample_n, ntop)
modelpvalues = pvaluelist$modelpvalues
rank_modelpvalues = pvaluelist$rank_modelpvalues
rm(pvaluelist)


pvaluegg = melt(modelpvalues, variable.name = "factor",
                value.name =  "p.value")
pvaluegg$depvar = factor(pvaluegg$depvar, levels = unique(pvaluegg$depvar))


stemcolono_values = stemcolono@meta.data[,grep("^nmf_", colnames(stemcolono@meta.data))]

stemcolono_scaled = apply(stemcolono_values, 2, scale)

stemcolono_scaled_means_id = aggregate(stemcolono_scaled, by = list(stemcolono$G_W), mean)
stemcolono_means_id = aggregate(stemcolono_values, by = list(stemcolono$G_W), mean)
stemcolono_means_scaled_id = as.data.frame(apply(stemcolono_means_id[,-1], 2, scale))
stemcolono_means_scaled_id$Group.1 = stemcolono_means_id$Group.1

stemcolono_scaled_means_cluster = aggregate(stemcolono_scaled, by = list(stemcolono$NamedCluster), mean)
stemcolono_means_cluster = aggregate(stemcolono_values, by = list(stemcolono$NamedCluster), mean)
if(nrow(stemcolono_means_cluster)==1){
  stemcolono_means_scaled_cluster = as.data.frame(rbind(apply(stemcolono_means_cluster[,-1], 2, scale)))
  stemcolono_means_scaled_cluster$Group.1 = stemcolono_means_cluster$Group.1
  stemcolono_means_scaled_cluster[1,is.nan(as.numeric(stemcolono_means_scaled_cluster[1,]))] = 0
}else{
  stemcolono_means_scaled_cluster = as.data.frame(apply(stemcolono_means_cluster[,-1], 2, scale))
  stemcolono_means_scaled_cluster$Group.1 = stemcolono_means_cluster$Group.1
}

```

```{r, fig.show="hide"}

ph_sample = pheatmap(stemcolono_means_scaled_id[,paste0("nmf_", 1:ntop)])

ph_order = ph_sample$tree_col$order

```

```{r, fig.width = 2.5, fig.height = 6}

my_dotp = ggplot(melt(stemcolono_means_scaled_id), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + 
  geom_vline(color = "white", xintercept = 1.5) +
  scale_fill_viridis_c() + 
  scale_y_discrete(labels = function(x){gsub("nmf_", "f",x)}) + 
  theme_classic() + 
  theme(axis.text = txt,
        axis.title = element_blank(),
        plot.title = element_blank(),
        legend.text = txt,
        legend.title = txt,
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5)) + 
  scale_size_continuous(limits = c(0,100), range= c(0,3))

my_dotp_cl = ggplot(melt(stemcolono_means_scaled_cluster), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c() +
  theme_classic() +
  theme(axis.text = txt,
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.text = txt,
        axis.text.y = element_blank(),
        legend.key.size = unit(8,"pt"),
        plot.title = element_blank(),
        legend.position = "bottom",
        legend.title = txt) + 
  scale_size_continuous(limits = c(0,100))

lmp = ggplot(pvaluegg,
       aes(y = factor(factor, levels = rev(paste0("nmf_",ph_order))), x = depvar)) + 
  geom_tile(aes(fill = -log10(p.value))) + 
  scale_fill_viridis_c(option = "inferno", na.value = "#FCFFA4FF", limits = c(0,NA)) + 
  scale_x_discrete(labels = function(x){gsub("SCID","",x)}) + 
  theme_classic() + 
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        legend.title = element_text(size = 8),
        legend.position = "bottom",
        legend.direction = "vertical",
        legend.text = element_text(size = 8),
        legend.key.size = unit(8,"pt"))

scalerange = c(min(my_dotp$data$value, my_dotp_cl$data$value),
               max(my_dotp$data$value, my_dotp_cl$data$value))

plot_grid(my_dotp + 
            scale_fill_viridis_c(limits = scalerange) + 
            theme(axis.title = element_blank(),
                  legend.position = "bottom",
                      legend.key.size = unit(8,"pt")),
          my_dotp_cl + 
            scale_fill_viridis_c(limits = scalerange),
          lmp + 
            labs(fill = ""), 
          align = "h", ncol = 3, rel_widths = c(3.5,2.5,1)
          )

```


```{r, fig.height = 2, fig.width = 4}

showfactors_Il10(stemcolono)

```


## Goblet cells



```{r}

ntop = 20
downsample_n = 500
txt = element_text(size = 8)

```


```{r}

goblet@active.assay <- "RNA"


goblet <- FindVariableFeatures(goblet)
goblet <- ScaleData(goblet, features = VariableFeatures(goblet))

goblet <- RunNMF(object = goblet, assay = "RNA", nfactors = ntop,
              n.cores = 1)
 

for(i in 1:ntop){
  goblet <- AddMetaData(goblet, goblet@reductions$NMF@cell.embeddings[,paste0("factor_",i)],
                     paste0("nmf_",i))
}

goblet$Week = as.numeric(gsub("W","",goblet$Week))

goblet = AddMetaData(goblet, factor(paste(goblet$Genotype, goblet$Week),
                              levels = c("WT 6", 
                                         paste0("Il10KO ", 
                                               c(6,8,10,12,14)))), 
                  "G_W")

```

```{r}

pvaluelist = getfactorpvalues_Il10(goblet, downsample_n, ntop)
modelpvalues = pvaluelist$modelpvalues
rank_modelpvalues = pvaluelist$rank_modelpvalues
rm(pvaluelist)


pvaluegg = melt(modelpvalues, variable.name = "factor",
                value.name =  "p.value")
pvaluegg$depvar = factor(pvaluegg$depvar, levels = unique(pvaluegg$depvar))


goblet_values = goblet@meta.data[,grep("^nmf_", colnames(goblet@meta.data))]

goblet_scaled = apply(goblet_values, 2, scale)

goblet_scaled_means_id = aggregate(goblet_scaled, by = list(goblet$G_W), mean)
goblet_means_id = aggregate(goblet_values, by = list(goblet$G_W), mean)
goblet_means_scaled_id = as.data.frame(apply(goblet_means_id[,-1], 2, scale))
goblet_means_scaled_id$Group.1 = goblet_means_id$Group.1

goblet_scaled_means_cluster = aggregate(goblet_scaled, by = list(goblet$NamedCluster), mean)
goblet_means_cluster = aggregate(goblet_values, by = list(goblet$NamedCluster), mean)
if(nrow(goblet_means_cluster)==1){
  goblet_means_scaled_cluster = as.data.frame(rbind(apply(goblet_means_cluster[,-1], 2, scale)))
  goblet_means_scaled_cluster$Group.1 = goblet_means_cluster$Group.1
  goblet_means_scaled_cluster[1,is.nan(as.numeric(goblet_means_scaled_cluster[1,]))] = 0
}else{
  goblet_means_scaled_cluster = as.data.frame(apply(goblet_means_cluster[,-1], 2, scale))
  goblet_means_scaled_cluster$Group.1 = goblet_means_cluster$Group.1
}

```

```{r, fig.show="hide"}

ph_sample = pheatmap(goblet_means_scaled_id[,paste0("nmf_", 1:ntop)])

ph_order = ph_sample$tree_col$order

```

```{r, fig.width = 2.6, fig.height = 6}



my_dotp = ggplot(melt(goblet_means_scaled_id), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + 
  geom_vline(color = "white", xintercept = 1.5) +
  scale_fill_viridis_c() + 
  scale_y_discrete(labels = function(x){gsub("nmf_", "f",x)}) + 
  theme_classic() + 
  theme(axis.text = txt,
        axis.title = element_blank(),
        plot.title = element_blank(),
        legend.text = txt,
        legend.title = txt,
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5)) + 
  scale_size_continuous(limits = c(0,100), range= c(0,3))

my_dotp_cl = ggplot(melt(goblet_means_scaled_cluster), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c() +
  theme_classic() +
  theme(axis.text = txt,
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.text = txt,
        axis.text.y = element_blank(),
        legend.key.size = unit(8,"pt"),
        plot.title = element_blank(),
        legend.position = "bottom",
        legend.title = txt) + 
  scale_size_continuous(limits = c(0,100))

lmp = ggplot(pvaluegg,
       aes(y = factor(factor, levels = rev(paste0("nmf_",ph_order))), x = depvar)) + 
  geom_tile(aes(fill = -log10(p.value))) + 
  scale_fill_viridis_c(option = "inferno", na.value = "#FCFFA4FF", limits = c(0,NA)) + 
  scale_x_discrete(labels = function(x){gsub("SCID","",x)}) + 
  theme_classic() + 
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        legend.title = element_text(size = 8),
        legend.position = "bottom",
        legend.direction = "vertical",
        legend.text = element_text(size = 8),
        legend.key.size = unit(8,"pt"))

scalerange = c(min(my_dotp$data$value, my_dotp_cl$data$value),
               max(my_dotp$data$value, my_dotp_cl$data$value))

plot_grid(my_dotp + 
            scale_fill_viridis_c(limits = scalerange) + 
            theme(axis.title = element_blank(),
                  legend.position = "bottom",
                      legend.key.size = unit(8,"pt")),
          my_dotp_cl + 
            scale_fill_viridis_c(limits = scalerange),
          lmp + 
            labs(fill = ""), 
          align = "h", ncol = 3, rel_widths = c(3.5,1.8,1)
          )

```


```{r, fig.height = 2, fig.width = 4}

showfactors_TCT(goblet)

```

# Session info

```{r}

sessionInfo()

```
