---
title: "T cell transfer single cell analysis - Immune fraction"
editor_options:
  chunk_output_type: console
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  bookdown::html_document2:
    code_folding: hide
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
params:
  dataset: 1
---

```{r Setup, echo = FALSE}
knitr::opts_chunk$set(fig.width  = 10,
                      results    = "hold",
                      message    = FALSE,
                      warning    = FALSE)


```

```{r setup}

library(Seurat)
library(ggplot2)
library(cowplot)
library(clustree)

library(future)
plan("sequential")
options(future.globals.maxSize = 50 * 1024^3)

if(!require("NNLM")){
  devtools::install_github('linxihui/NNLM')
}

source("../code/SingleCell/color_list.R")
source("../code/SingleCell/NMFsetup.R", chdir = TRUE)

txt = element_text(size = 8)


```

```{r}
 
datadir = "../data/SingleCell/TcellTransfer/R_objects/"

owncache = "../data/SingleCell/TcellTransfer/cache_immune/"

violintheme = theme(axis.text = element_text(size = 8),
        plot.title = element_text(size = 8),
        legend.key.size = unit(8, "pt"),
        axis.title = element_blank())
dimtheme = theme(legend.text = element_text(size = 8),
        plot.title = element_text(size = 8),
        legend.key.size = unit(8, "pt"))

qc_feats <- c("nFeature_RNA", "nCount_RNA", "percent_mito", "percent_ribo")

```

```{r, include = FALSE}

if(file.exists(owncache)){
  message(paste0("Intermediate data files will be loaded from and saved to ",owncache))
}else{
  message("Intermediate data files will not be saved or loaded")
}

```

# Initial data 


```{r loaddata}

if(!file.exists(paste0(owncache,"first_dr.RData"))){
  alldata = readRDS(paste0(datadir,"immune_data.rds"))

DefaultAssay(alldata) = "RNA"

suppressWarnings(
  suppressMessages(
    alldata <-FindVariableFeatures(alldata, selection.method = "vst", 
                                   nfeatures = 2000, verbose = FALSE,
                                   assay = "RNA")))

  alldata <- ScaleData(alldata, vars.to.regress = c("percent_mito", "nFeature_RNA"), 
      assay = "RNA")
  alldata <- RunPCA(alldata, npcs = 50, verbose = F)
  alldata <- RunUMAP(alldata, reduction = "pca", dims = 1:30, 
                     n.components = 2, n.neighbors = 30, 
      n.epochs = 200, min.dist = 0.3, learning.rate = 1, 
      spread = 1, reduction.name = "umap")
  
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache,"first_dr.RData"))
  }
}else{
  load(paste0(owncache,"first_dr.RData"))
}


```


# Plot QC vars

Number of features and counts and percentage of mitochondrial and ribosomal RNA are plotted below.

```{r qc, fig.height=4, fig.width=6}

VlnPlot(alldata, group.by = "orig.ident", features = qc_feats, pt.size = 0, ncol = 2) &
  violintheme

```

# Highly variable features

```{r topgenes, fig.height = 3, fig.width = 5}

top20 <- head(VariableFeatures(alldata), 20)
lp = LabelPoints(plot = VariableFeaturePlot(alldata), points = top20, repel = TRUE) +
  theme(axis.title = element_text(size = 8),
        legend.text = element_text(size = 8),
        axis.text = element_text(size = 8))

lp$layers[[2]]$aes_params$size = 3

lp

```

# PCA

```{r, fig.height = 3, fig.width = 6}

plot_grid(ncol = 3, 
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident", 
                  dims = 1:2, shuffle = TRUE) +
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)),
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident", 
                  dims = 3:4, shuffle = TRUE) + 
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)),
          DimPlot(alldata, reduction = "pca", group.by = "orig.ident",
                  dims = 5:6, shuffle = TRUE) + 
            NoLegend() + dimtheme + 
            theme(axis.text = element_text(size = 8),
                  axis.title = element_text(size = 8)))

```


```{r, fig.height = 3, fig.width = 6}

VizDimLoadings(alldata, dims = 1:5, reduction = "pca", ncol = 5, balanced = T) &
  theme(axis.text = element_text(size = 8), axis.title = element_text(size = 8))

```


```{r, fig.height = 2, fig.width = 4}

ElbowPlot(alldata, reduction = "pca", ndims = 50) + 
  theme(axis.text = element_text(size = 8),
        axis.title = element_text(size = 8))

```

# UMAP

```{r firstumap, fig.height = 3, fig.width = 6}

plot_grid(ncol = 2, DimPlot(alldata, reduction = "pca", raster = TRUE,
                            group.by = "orig.ident", shuffle = TRUE) + 
            NoLegend() + NoAxes() + dimtheme, 
    DimPlot(alldata, reduction = "umap", group.by = "orig.ident", raster = TRUE,
            shuffle = TRUE) +
      NoLegend() + NoAxes() + dimtheme)

plot_grid(ncol = 2, DimPlot(alldata, reduction = "umap", raster = TRUE,
                            group.by = "orig.ident", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme, 
          DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "Model", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme)

plot_grid(ncol = 2, DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "Treatment", shuffle = TRUE) +
            theme(legend.position = "bottom") + NoAxes() + dimtheme,
          DimPlot(alldata, reduction = "umap", raster = TRUE,
                  group.by = "RPCA_cluster", label = TRUE, shuffle = TRUE) + 
            NoLegend() + NoAxes() + dimtheme)

FeaturePlot(alldata, reduction = "umap", features = c("Ptprc","Epcam"), raster = TRUE,
    order = T, slot = "data", combine = T) & dimtheme & NoAxes() & NoLegend()

```


# Integration


```{r}


plan("multisession", workers = 6)


if(!file.exists(paste0(owncache,"integration.RData"))){
  if(!file.exists(paste0(owncache,"anchors.RData"))){

    # Works with 256GB on 6 workers
    alldata <- SplitObject(alldata, split.by = "orig.ident")
    
    alldata = lapply(alldata, function(x){
        x <- NormalizeData(x, verbose = FALSE)
        x <- FindVariableFeatures(x, selection.method = "vst",
                nfeatures = 2000, verbose = FALSE)
      })
        
    data.anchors <- FindIntegrationAnchors(object.list = alldata, 
                                                dims = 1:30, reduction = "cca")
    rm(alldata)
    gc()

    if(file.exists(owncache)){
          save(data.anchors, file = paste0(owncache,"anchors.RData"))
    }
  }else{
    rm(alldata)
    gc()
    load(paste0(owncache,"anchors.RData"))
  }
  
  plan("sequential")
  
  # works with 256GB in sequential 
  alldata <- IntegrateData(anchorset = data.anchors, dims = 1:30, new.assay.name = "CCA",
     sample.tree = cbind(c(-4,-1,2,3,-8,5,-10,7,-15,9,4,8,11,12),
                         c(-5,-2,-3,1,-7,-6,-11,-12,-14,-13,6,10,-9,13)))
  
  rm(data.anchors)
  gc()
  
  alldata <- ScaleData(alldata)
  alldata <- RunPCA(alldata, npcs = 30, verbose = FALSE)
  alldata <- RunUMAP(alldata, dims = 1:30)
  
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache,"integration.RData"))
  }
}else{
  load(paste0(owncache,"integration.RData"))
}

plan("sequential")

```

```{r, fig.height = 2, fig.width=5}

plot_grid(ncol = 2,
  
  DimPlot(alldata, reduction = "pca", group.by = "orig.ident", pt.size = 0.01, shuffle = TRUE) +
    NoAxes() + ggtitle("PCA integrated") + NoLegend() + dimtheme,
  DimPlot(alldata, reduction = "umap", group.by = "orig.ident", pt.size = 0.01, shuffle = TRUE) +
    NoAxes() + ggtitle("UMAP integrated") + NoLegend() + dimtheme
)

alldata@active.assay = "RNA"
FeaturePlot(alldata, reduction = "umap", features = c("Ptprc","Epcam"), 
    order = T, slot = "data", combine = T) & dimtheme & NoAxes()
alldata@active.assay = "CCA"

```



```{r, fig.height = 6, fig.width=4}

FeaturePlot(alldata, reduction = "umap", 
            features = c("percent_mito","percent_ribo","S.Score",
                         "G2M.Score", "nFeature_RNA"), 
    order = T, slot = "data", combine = T, ncol = 2) &
  NoAxes() & NoLegend() & dimtheme

```



# Clustering

```{r}

if(!file.exists(paste0(owncache, "clustered.RData"))){
  alldata@active.assay <- "CCA"
  
  alldata@active.assay

  alldata <- FindNeighbors(alldata, dims = 1:30, k.param = 350, prune.SNN = 1/15)

  
  # Clustering with louvain (algorithm 1)
  for (res in c(0.25, 0.5, 1, 1.5)) {
      alldata <- FindClusters(alldata, graph.name = "CCA_snn",
                              resolution = res, algorithm = 1)
  }
  if(file.exists(owncache)){
    save(alldata, file = paste0(owncache, "clustered.RData"))
  }
}else{
  load(paste0(owncache, "clustered.RData"))
}



```



```{r dimplots, fig.height=6, fig.width = 6}

plot_grid(ncol = 2, 
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.0.25",
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_0.25"),
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.0.5", 
                  label = TRUE) + dimtheme +  NoLegend() + NoAxes() + 
            ggtitle("louvain_0.5"),
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.1", 
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_1"), 
          DimPlot(alldata, reduction = "umap", group.by = "CCA_snn_res.1.5", 
                  label = TRUE) + dimtheme + NoLegend() + NoAxes() + 
            ggtitle("louvain_1.5"))


```


```{r clustreeplot}

clustree(alldata@meta.data, prefix = "CCA_snn_res.")

```


```{r}

clusternames = 
  data.frame(Cluster = c(0:16),
             Clustername = c("CD4+ T cells Emb","Monocytes",
                             "Cytotoxic CD4+","Macrophages Apoe",
                             "NK","ILC2","ILC3","Proliferating",
                             "Low counts","DC1","Neutrophils",
                             "Mature DC","Treg","Mast cells",
                             "Macrophages Retnla","pDC",
                             "IFN response CD4+"))

clusterorder = 
  c("CD4+ T cells Emb","Cytotoxic CD4+","Treg","IFN response CD4+",
    "Proliferating","ILC2","ILC3","NK","Monocytes","Macrophages Apoe",
    "Macrophages Retnla","DC1","Mature DC","pDC","Neutrophils",
    "Mast cells","Low counts")

alldata = AddMetaData(alldata, 
                      factor(clusternames$Clustername[
                        match(alldata$CCA_snn_res.0.5,clusternames$Cluster)], 
                        levels = clusterorder),
                      "NamedCluster")

alldata = SetIdent(alldata, value = "NamedCluster")

color_list = get_color_list(length(clusternames$Clustername))
names(color_list) = clusterorder

```

```{r, fig.height = 4, fig.width = 4}

dp = DimPlot(alldata, label = TRUE, shuffle = TRUE) + 
  NoAxes() + NoLegend() + dimtheme + scale_color_manual(values = color_list)

dp$layers[[2]]$aes_params$size = 3

dp

```

# Differential expression


```{r}


alldata@active.assay = "RNA"
alldata = NormalizeData(alldata)
alldata = FindVariableFeatures(alldata)

# Becomes slower when parallel

plan("sequential")

if(!file.exists(paste0(owncache, "clustermarkers.rds"))){
  markers_genes <- FindAllMarkers(alldata, logfc.threshold = 0.2, test.use = "wilcox", 
    min.pct = 0.1, min.diff.pct = 0.2, only.pos = TRUE, max.cells.per.ident = 1000, 
    assay = "RNA", random.seed = 42)
            
  if(file.exists(owncache)){
    saveRDS(markers_genes, paste0(owncache, "clustermarkers.rds"))
  }
}else{
   markers_genes = readRDS(paste0(owncache, "clustermarkers.rds"))
}

top25 <- markers_genes %>% group_by(cluster) %>% top_n(-25, p_val)

out = lapply(unique(top25$cluster), function(i){
  markersdata = top25[top25$cluster==i,]
  markersdata$gene = factor(markersdata$gene, levels = rev(markersdata$gene))
  print(ggplot(markersdata, aes(x = avg_log2FC, y = gene)) + 
          labs(title = i) + 
    geom_bar(stat = "identity") + 
    theme(axis.title.y = element_blank(),
          axis.title.x = element_text(size = 8),
          plot.title = element_text(size = 8),
          axis.text = element_text(size = 8)))
})

```


```{r}

markergenes = c('Icos', 'Il7r', 'Cd3d', 'Cd3e', 'Cd3g', 'Cd4',
                'Emb', 'Lef1', 'Cxcr6', 'Ccl5', 'Eomes', 'Gzmk',
                'Cd8a', 'Tnfrsf4', 'Ctla4', 'Foxp3', 'Tnfsf8',
                'Ifit1', 'Zbp1', 'Stmn1', 'Mki67', 'Gata3', 'Areg', 
                'Il22', 'Nrgn', 'Gpr183', 'Ncr1', 'Xcl1', 'Klrc1',
                'Cd19', 'Ms4a1', 'Bank1', 'Jchain', 'Mzb1', 'Cd14',
                'Csf1r', 'Lyz2', 'Ms4a6d', 'Apoe', 'C1qa', 'Mafb',
                'Retnla', 'Fn1', 'Cd74', 'Ly6c2', 'Xcr1', 'Cd86',
                'Ccr7', 'Irf8', 'Bst2', 'Siglech', 'S100a9', 'S100a8',
                'Cpa3', 'Mcpt1', 'Retnlg'
)

```

```{r dotplot, fig.height = 2.2, fig.width = 6}

alldata@active.assay = "RNA"

alldata@active.ident = factor(alldata$NamedCluster, levels = clusterorder)
dot = DotPlot(alldata, features=rev(markergenes))
dot = dot + aes(x = id, y = features.plot) + scale_x_discrete(position = "top") + 
  labs(y = "Genes",x = "Clusters") + 
  scale_size(range = c(0.5,2.5), breaks = c(0,50,100), limits = c(0,100)) +
  theme(legend.position = "none", legend.title = element_blank(),
        axis.text.x = element_text(size = 6, angle = 90, hjust = 0),
        axis.text.y = element_text(size = 6, face = "italic"),
        legend.key.width = unit(0.3, "cm"), 
        legend.key.height = unit(0.3,"cm"), 
        legend.text = element_text(size = 6),
        axis.title = element_text(size = 8)) 

dot$scales$scales[[1]]$limits = c(-1.8,2.7)

print(dot)

plot_grid(get_legend(dot + theme(legend.position = "bottom")))

```


# CITE-seq

```{r}

DefaultAssay(alldata) = "FB"

alldata <- NormalizeData(alldata)
alldata <- ScaleData(alldata)
  
```



```{r, fig.height = 2.2, fig.width = 2.3}

alldata@active.assay <- "FB"

dot = DotPlot(alldata, assay = "FB", features = rev(rownames(alldata)), 
              group.by = "NamedCluster") 
dot = dot + aes(x = id, y = features.plot) + scale_x_discrete(position = "top") +
  labs(y = "Antibodies",x = "Clusters") +
  scale_size(range = c(0.1,2.5), breaks = c(60,80,100)) +
  theme(legend.position = "bottom", legend.title = element_blank(),
        axis.text.x = element_text(size = 6, hjust = 0, angle = 90),
        axis.text.y = element_text(size = 6),
        legend.key.width = unit(0.3, "cm"),
        legend.key.height = unit(0.3,"cm"),
        legend.text = element_text(size = 6),
        axis.title.y = element_text(size = 8),
        axis.title.x = element_blank()) +
  scale_y_discrete(labels = function(x){gsub("-TotalSeqB","",x)})

dot + theme(legend.position = "none")
plot_grid(get_legend(dot))

```


# Population changes over time

```{r}

clean_sample_names = function(sam){
  for(s in c("_Imm","I_","_Epi","_E","_Str","S_","_ut","G_", "_aIL12","_il")){
    sam = gsub(s, "",sam)
  }
  sam
}

```



```{r}

alldata$Treatment = factor(alldata$Treatment,
                           levels = c("ut","il"))

frequencies = as.data.frame(table(data.frame(cluster=alldata$NamedCluster,
                 sample = alldata$orig.ident, model = alldata$Model)))
frequencies$Proportion=NA
for(i in 1:nrow(frequencies)){
  frequencies$Proportion[i] =
    frequencies$Freq[i]/
    sum(frequencies$Freq[frequencies$sample==frequencies$sample[i]])
}

frequencies$time = alldata$Time[match(frequencies$sample,
                                      alldata$orig.ident)]
frequencies$treatment = 
  alldata$Treatment[match(frequencies$sample, 
                          alldata$orig.ident)]

frequencies = frequencies[
  (substr(frequencies$time,1,1) == "W" & frequencies$model == "SCID") |
    (substr(frequencies$time,1,1) == "D" & frequencies$model == "Rag2"),]


clustercors = lapply(c("SCID","Rag2"), function(bg){
  corlist = lapply(unique(frequencies$cluster), function(i){
    clufreq = frequencies[frequencies$cluster==i  & 
                          frequencies$treatment == "ut" & 
                          frequencies$model == bg,]

    clucor = cor(clufreq$Proportion,as.numeric(
      as.factor(as.character(clufreq$time))))
    clucor
    })
  names(corlist) = unique(frequencies$cluster)
  corlist
  })
names(clustercors) = c("SCID","Rag2")

averagecor = lapply(1:length(clustercors[[1]]), function(i){
  mean(c(clustercors[[1]][[i]], clustercors[[2]][[i]]))
})
names(averagecor) = names(clustercors[[1]])

frequencies$cluster = 
  factor(frequencies$cluster, 
         levels = names(averagecor)[order(unlist(averagecor),
                                          decreasing = TRUE)])

frequencies$sample = 
  factor(frequencies$sample, 
         levels = 
           unique(frequencies$sample[
             order(factor(frequencies$model, levels = c("SCID","Rag2")),
                   frequencies$treatment,
                   frequencies$time)]))
frequencies$samplenumber = as.numeric(frequencies$sample)


cumulFreq = frequencies
cumulFreq$cumulProp = NA
for(i in unique(cumulFreq$sample)){
  cumulFreq$cumulProp[cumulFreq$sample %in% i] = rev(cumsum(rev(cumulFreq$Proportion[cumulFreq$sample %in% i])))
}
cumulFreq = rbind(cumulFreq,cumulFreq)
cumulFreq$xadj = rep(c(-1,1), c(nrow(frequencies),nrow(frequencies)))
cumulFreq$oldtime = cumulFreq$time
cumulFreq$time = as.numeric(
  gsub("D","",gsub("W","",as.character(cumulFreq$time))))


datasets = lapply(names(clustercors), function(bg){
  bgfreq = frequencies[frequencies$model == bg,]
  bglist = lapply(unique(bgfreq$treatment), function(i){
    trfr = bgfreq[bgfreq$treatment==i,]
    cumtrfr = cumulFreq[paste(cumulFreq$sample,
                                     cumulFreq$model,
                                     cumulFreq$oldtime) %in% 
                                 paste(trfr$sample,
                                       trfr$model,
                                       trfr$time),]
    list(trfr, cumtrfr)
  })
  names(bglist) = unique(bgfreq$treatment)
  bglist
})

barplot = ggplot(data = frequencies, 
       aes(x = samplenumber, y = Proportion, fill = cluster)) + 
  theme(panel.background = element_blank(), axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
            scale_fill_manual(
              values =
                color_list[as.character(unique(sort(frequencies$cluster)))]) + 
            scale_x_continuous(
              breaks = sort(unique(frequencies$samplenumber)),
              labels = clean_sample_names(levels(frequencies$sample)))

for(ds in datasets){
  for(dst in ds){
    barplot = barplot + 
      geom_area(data = dst[[2]],
                alpha = 0.7, size = 0.3, stat = 'identity',
                aes(fill = cluster, group = cluster,
                    y = Proportion, x = samplenumber + xadj*0.3))}
}

barplot + geom_bar(stat = "identity", width = 0.6, color = "black")

```

# Subset analyses

```{r}

DefaultAssay(alldata) = "RNA"

alldata$ModelTreatmentTime = paste(alldata$Model, 
                                     alldata$Treatment, 
                                     alldata$Time)
alldata$ModelTreatmentTime = factor(alldata$ModelTreatmentTime,
      levels = unique(alldata$ModelTreatmentTime[order(
        factor(alldata$Model, levels = c("SCID", "Rag2")),
        factor(alldata$Treatment, levels = c("ut","il")),
        alldata$Time)]))
alldata$ModelTreatment = paste(alldata$Model, 
                                     alldata$Treatment)
alldata$ModelTreatment = factor(alldata$ModelTreatment,
      levels = unique(alldata$ModelTreatment[order(
        factor(alldata$Model, levels = c("SCID", "Rag2")),
        factor(alldata$Treatment, levels = c("ut","il")))]))

alldata = AddMetaData(alldata, alldata$NamedCluster, "CD4Tcells")
alldata = AddMetaData(alldata, alldata$NamedCluster, "neutrophils")

alldata$CD4Tcells[!(alldata$CD4Tcells %in% 
                  c("CD4+ T cells Emb","Cytotoxic CD4+",
                    "Treg","IFN response CD4+"))] = NA
alldata$CD4Tcells[alldata$RelTime < 0.1] = NA

alldata$neutrophils[!(alldata$neutrophils %in% 
                  c("Neutrophils"))] = NA

```

```{r, fig.height = 3, fig.width = 6}

plot_grid(plotlist = lapply(c("CD4Tcells","neutrophils"),
       function(x){
         dp = DimPlot(alldata, group.by = x, label = TRUE, shuffle = TRUE) +
            scale_color_manual(values = color_list, na.value = "#CACACA") +
            dimtheme & NoLegend() & NoAxes()
         dp$layers[[2]]$aes_params$size = 3
         dp
       }), ncol = 2)

```

```{r}

alldata@active.assay <- "RNA"
alldata[["CCA"]] = NULL

alldata <- FindVariableFeatures(alldata)
alldata <- ScaleData(alldata, features = VariableFeatures(alldata))

CD4Tcells = 
  subset(alldata, 
         cells = WhichCells(
           alldata, expression = 
             CD4Tcells %in% alldata$NamedCluster))
neutrophils = 
  subset(alldata, 
         cells = WhichCells(
           alldata, 
           expression = neutrophils %in% alldata$NamedCluster))

rm(alldata)
gc()

```



# NMF



## CD4 T cells

```{r CD4NMF}

ntop = 40
downsample_n = 500

if(!file.exists(paste0(owncache,"CD4_NMF.RData"))){

  CD4Tcells@active.assay <- "RNA"
  
  CD4Tcells <- FindVariableFeatures(CD4Tcells)
  CD4Tcells <- ScaleData(CD4Tcells, features = VariableFeatures(CD4Tcells))
  
  CD4Tcells <- RunNMF(object = CD4Tcells, assay = "RNA", nfactors = ntop,
                  n.cores = 1)
  
  if(file.exists(owncache)){
    save(CD4Tcells, file = paste0(owncache, "CD4_NMF.RData"))
  }
}else{
   load(paste0(owncache, "CD4_NMF.RData"))
}


```

```{r}

for(i in 1:ntop){
  CD4Tcells <- 
    AddMetaData(CD4Tcells, 
                CD4Tcells@reductions$NMF@cell.embeddings[,paste0("factor_",i)],
                paste0("nmf_",i))
}


```





```{r}

modelpvalues = getfactorpvalues_TCT(CD4Tcells, downsample = downsample_n, ntop)

pvaluegg = melt(modelpvalues, variable.name = "factor",
                value.name =  "p.value")
pvaluegg$depvar = factor(pvaluegg$depvar, levels = unique(pvaluegg$depvar))


CD4Tcells_values = CD4Tcells@meta.data[,grep("^nmf_", colnames(CD4Tcells@meta.data))]

CD4Tcells_scaled = apply(CD4Tcells_values, 2, scale)

CD4Tcells_scaled_means_id = 
  aggregate(CD4Tcells_scaled, 
            by = list(CD4Tcells$ModelTreatmentTime), mean)
CD4Tcells_means_id = 
  aggregate(CD4Tcells_values, 
            by = list(CD4Tcells$ModelTreatmentTime), mean)
CD4Tcells_means_scaled_id = as.data.frame(apply(CD4Tcells_means_id[,-1], 2, scale))
CD4Tcells_means_scaled_id$Group.1 = CD4Tcells_means_id$Group.1

CD4Tcells_scaled_means_cluster = aggregate(CD4Tcells_scaled, by = list(CD4Tcells$NamedCluster), mean)
CD4Tcells_means_cluster = aggregate(CD4Tcells_values, by = list(CD4Tcells$NamedCluster), mean)
if(nrow(CD4Tcells_means_cluster)==1){
  CD4Tcells_means_scaled_cluster = as.data.frame(rbind(apply(CD4Tcells_means_cluster[,-1], 2, scale)))
  CD4Tcells_means_scaled_cluster$Group.1 = CD4Tcells_means_cluster$Group.1
  CD4Tcells_means_scaled_cluster[1,is.nan(as.numeric(CD4Tcells_means_scaled_cluster[1,]))] = 0
}else{
  CD4Tcells_means_scaled_cluster = as.data.frame(apply(CD4Tcells_means_cluster[,-1], 2, scale))
  CD4Tcells_means_scaled_cluster$Group.1 = CD4Tcells_means_cluster$Group.1
}

```


```{r, fig.show="hide"}

ph_sample = pheatmap(CD4Tcells_means_scaled_id[,paste0("nmf_", 1:ntop)])

ph_order = ph_sample$tree_col$order

```

```{r, fig.width = 2.5, fig.height = 6}

my_dotp = ggplot(melt(CD4Tcells_means_scaled_id), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + 
  geom_vline(color = "white", xintercept = c(7.5,8.5)) +
  scale_fill_viridis_c() + 
  scale_y_discrete(labels = function(x){gsub("nmf_", "f",x)}) + 
  theme_classic() + 
  theme(axis.text = txt,
        axis.title = element_blank(),
        plot.title = element_blank(),
        legend.text = txt,
        legend.title = txt,
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5)) + 
  scale_size_continuous(limits = c(0,100), range= c(0,3))

my_dotp_cl = ggplot(melt(CD4Tcells_means_scaled_cluster), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c() +
  theme_classic() +
  theme(axis.text = txt,
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.text = txt,
        axis.text.y = element_blank(),
        legend.key.size = unit(8,"pt"),
        plot.title = element_blank(),
        legend.position = "bottom",
        legend.title = txt) + 
  scale_size_continuous(limits = c(0,100))

lmp = ggplot(pvaluegg,
       aes(y = factor(factor, levels = rev(paste0("nmf_",ph_order))), x = depvar)) + 
  geom_tile(aes(fill = -log10(p.value))) + 
  scale_fill_viridis_c(option = "inferno", na.value = "#FCFFA4FF", limits = c(0,NA)) + 
  scale_x_discrete(labels = function(x){gsub("SCID","",x)}) + 
  theme_classic() + 
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        legend.title = element_text(size = 8),
        legend.position = "bottom",
        legend.direction = "vertical",
        legend.text = element_text(size = 8),
        legend.key.size = unit(8,"pt"))

scalerange = c(min(my_dotp$data$value, my_dotp_cl$data$value),
               max(my_dotp$data$value, my_dotp_cl$data$value))

plot_grid(my_dotp + 
            scale_fill_viridis_c(limits = scalerange) + 
            theme(axis.title = element_blank(),
                  legend.position = "bottom",
                      legend.key.size = unit(8,"pt")),
          my_dotp_cl + 
            scale_fill_viridis_c(limits = scalerange),
          lmp + 
            labs(fill = ""), 
          align = "h", ncol = 3, rel_widths = c(3.5,2.7,1)
          )

```

```{r, fig.height = 2, fig.width = 4}

showfactors_TCT(SplitObject(CD4Tcells, split.by = "ModelTreatment"),
                relvln = c(4,1))

```



## Neutrophils

```{r neutroNMF}

ntop = 20
downsample_n = 1000

if(!file.exists(paste0(owncache,"neutrophil_NMF.RData"))){

  neutrophils@active.assay <- "RNA"
  
  neutrophils <- FindVariableFeatures(neutrophils)
  neutrophils <- ScaleData(neutrophils, features = VariableFeatures(neutrophils))
  
  neutrophils <- RunNMF(object = neutrophils, assay = "RNA", nfactors = ntop,
                  n.cores = 1)
  
  if(file.exists(owncache)){
    save(neutrophils, file = paste0(owncache, "neutrophil_NMF.RData"))
  }
}else{
   load(paste0(owncache, "neutrophil_NMF.RData"))
}


```

```{r}

for(i in 1:ntop){
  neutrophils <- 
    AddMetaData(neutrophils, 
                neutrophils@reductions$NMF@cell.embeddings[,paste0("factor_",i)],
                paste0("nmf_",i))
}


```





```{r}

modelpvalues = getfactorpvalues_TCT(neutrophils, downsample = downsample_n, ntop)

pvaluegg = melt(modelpvalues, variable.name = "factor",
                value.name =  "p.value")
pvaluegg$depvar = factor(pvaluegg$depvar, levels = unique(pvaluegg$depvar))


neutrophils_values = neutrophils@meta.data[,grep("^nmf_", colnames(neutrophils@meta.data))]

neutrophils_scaled = apply(neutrophils_values, 2, scale)

neutrophils_scaled_means_id = 
  aggregate(neutrophils_scaled, 
            by = list(neutrophils$ModelTreatmentTime), mean)
neutrophils_means_id = 
  aggregate(neutrophils_values, 
            by = list(neutrophils$ModelTreatmentTime), mean)
neutrophils_means_scaled_id = as.data.frame(apply(neutrophils_means_id[,-1], 2, scale))
neutrophils_means_scaled_id$Group.1 = neutrophils_means_id$Group.1

neutrophils_scaled_means_cluster = aggregate(neutrophils_scaled, by = list(neutrophils$NamedCluster), mean)
neutrophils_means_cluster = aggregate(neutrophils_values, by = list(neutrophils$NamedCluster), mean)
if(nrow(neutrophils_means_cluster)==1){
  neutrophils_means_scaled_cluster = as.data.frame(rbind(apply(neutrophils_means_cluster[,-1], 2, scale)))
  neutrophils_means_scaled_cluster$Group.1 = neutrophils_means_cluster$Group.1
  neutrophils_means_scaled_cluster[1,is.nan(as.numeric(neutrophils_means_scaled_cluster[1,]))] = 0
}else{
  neutrophils_means_scaled_cluster = as.data.frame(apply(neutrophils_means_cluster[,-1], 2, scale))
  neutrophils_means_scaled_cluster$Group.1 = neutrophils_means_cluster$Group.1
}

```


```{r, fig.show="hide"}

ph_sample = pheatmap(neutrophils_means_scaled_id[,paste0("nmf_", 1:ntop)])

ph_order = ph_sample$tree_col$order

```

```{r, fig.width = 1.5, fig.height = 6}

my_dotp = ggplot(melt(neutrophils_means_scaled_id), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + 
  geom_vline(color = "white", xintercept = c(7.5,8.5)) +
  scale_fill_viridis_c() + 
  scale_y_discrete(labels = function(x){gsub("nmf_", "f",x)}) + 
  theme_classic() + 
  theme(axis.text = txt,
        axis.title = element_blank(),
        plot.title = element_blank(),
        legend.text = txt,
        legend.title = txt,
        axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5)) + 
  scale_size_continuous(limits = c(0,100), range= c(0,3))

my_dotp_cl = ggplot(melt(neutrophils_means_scaled_cluster), 
                 aes(x = Group.1, 
                     y = factor(variable, 
                                levels = rev(paste0("nmf_",ph_order))))) +
  geom_tile(aes(fill = value)) + scale_fill_viridis_c() +
  theme_classic() +
  theme(axis.text = txt,
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5),
        axis.title = element_blank(),
        legend.text = txt,
        axis.text.y = element_blank(),
        legend.key.size = unit(8,"pt"),
        plot.title = element_blank(),
        legend.position = "bottom",
        legend.title = txt) + 
  scale_size_continuous(limits = c(0,100))

lmp = ggplot(pvaluegg,
       aes(y = factor(factor, levels = rev(paste0("nmf_",ph_order))), x = depvar)) + 
  geom_tile(aes(fill = -log10(p.value))) + 
  scale_fill_viridis_c(option = "inferno", na.value = "#FCFFA4FF", limits = c(0,NA)) + 
  scale_x_discrete(labels = function(x){gsub("SCID","",x)}) + 
  theme_classic() + 
  theme(axis.text.x = element_text(size = 8, angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_blank(),
        axis.title = element_blank(),
        legend.title = element_text(size = 8),
        legend.position = "bottom",
        legend.direction = "vertical",
        legend.text = element_text(size = 8),
        legend.key.size = unit(8,"pt"))

scalerange = c(min(my_dotp$data$value, my_dotp_cl$data$value),
               max(my_dotp$data$value, my_dotp_cl$data$value))

plot_grid(my_dotp + 
            scale_fill_viridis_c(limits = scalerange) + 
            theme(axis.title = element_blank(),
                  legend.position = "bottom",
                      legend.key.size = unit(8,"pt")),
          lmp + 
            labs(fill = ""), 
          align = "h", ncol = 2, rel_widths = c(3.5,1)
          )

```

```{r, fig.height = 2, fig.width = 4}

showfactors_TCT(SplitObject(neutrophils, split.by = "ModelTreatment"),
                relvln = c(4,1))

```




# Session info

```{r}

sessionInfo()

```
